appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a7d1578b0700305bae
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: VF1vFcpadq7VnOQifR2vIgooXg8NbngdwDYhxWV53LrEnkEQFC6LJICk37V6J0cQzj8w0rgybjW5VxsHEQz8jV1ogMOhzBju+a4mBa3HxxTRl1FFpMQL59P5PiJnpW9VCXM4zayW4wybMT23E3f1NLeMZLeGkCF1tfTphksqXE7tkQAt5vUC2MxNsyuiFHJxrFaTr9suqSs0zQJUr/PcKnwxri35m9+V6t9e/K4yU+Hf3kj5PtqVla9Ubzw4JBo1DowVA+i+tLmFOOYvVm7Xlh5PwX0ywmv+UKBv1ixMWlCzXs0Lo+/ouw1t1N3u1NW6SYqv5GD/ActMPsqvWfLKnXzXJ5VIZ5u1/jIEqrDaYyRJZhetE9zlDaYFL7GW4EKVyVUtYDa0+pDa+Eoi24pAfZXuQ+3zeEQyg4Elt/4z5uNp9Sjk9SvLjehrAF1mBtyGeqrssmwaWRpOMoZEmisHEBA4LCUzdkb5bKUlK828ctz41tC5M1/8HSdnu3xC3stPM5w9mcfcPgUDkLKCG4PVc7lv45c6xBCJQIoko8MWZiCqw/1Detsk5647/1mqq2HY3GAyhErN/nKIKTKEaduV2hVyV5yBNGKn8nGXsYRfEEzSCkJdQL695uVGBuQsPVKe07RoLQJusoI+YUJDoMuQqf4JuDs3NieuyYobP5ZNwhM=}
